## FOOD_PRODUCT : 식품 정보 FOOD_ORDER  : 식품 주문 정보

## 생산일자가 2022년 5월인 식품들의 식품ID, 식품이름, 총매출 
## 총매출 내림차순, 식품ID 오름차순

SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, SUM(PRO.PRICE * ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT PRO
LEFT JOIN FOOD_ORDER ORD USING(PRODUCT_ID)
WHERE ORD.PRODUCE_DATE LIKE '2022-05-%'
GROUP BY PRO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID