## ONLINE_SALE : 온라인 상품 판매 정보
## OFFLINE_SALE  : 오프라인 상품 판매 정보

## 2022년 3월 오프/온라인 상품 판매 데이터의 판매 날짜, 상품 ID, 유저 ID, 판매량 출력
## OFFLINE_SALE 의 USER_ID 은 NULL 표시
## 판매일 기준 오름차순 -> 상품 ID 오름차순 -> 유저 ID 오름차순

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = "2022" AND MONTH(SALES_DATE) = 3
UNION
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE YEAR(SALES_DATE) = "2022" AND MONTH(SALES_DATE) = 3
ORDER BY 1,2,3