## CAR_RENTAL_COMPANY_RENTAL_HISTORY : 자동차 대여 기록 정보 테이블
## 대여 시작일 기준으로 2022년 8월부터 2022년 10월까지
## 총 대여 횟수 5회 이상
## 월별 자동차 ID 별 총 대여 횟수
## 월 기준 오름차순 -> 자동차 ID 내림차순
## 특정 월의 총 대여 횟수가 0 -> 결과 제외

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    CAR_ID IN (SELECT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
              GROUP BY CAR_ID
              HAVING COUNT(CAR_ID) >= 5)
    AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC