## BOOK : 도서 정보 테이블
## AUTHOR : 도서 저자 정보 테이블

## '경제' 카테고리(BOOK) 속하는 도서 ID(BOOK -> BOOK_ID), 저자명(AUTHOR -> AUTOHR_NAME), 출판일 리스트(BOOK -> PUBLISHED_DATE)
## 출판일 기준 오름차순 정렬

SELECT BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK JOIN AUTHOR
USING(AUTHOR_ID)
WHERE BOOK.CATEGORY = "경제"
ORDER BY PUBLISHED_DATE;

















# SELECT
#     BOOK_ID,
#     B.AUTHOR_NAME,
#     DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
#     # CATEGORY
# FROM BOOK A JOIN AUTHOR B
# USING(AUTHOR_ID)
# WHERE A.CATEGORY = "경제"
# ORDER BY PUBLISHED_DATE;