## REST_INFO : 식당 정보
## REST_REVIEW : 리뷰

## 서울에 위치한 식당들의 식당ID REST_ID , 식당 이름 REST_NAME, 음식 종류 FOOD_TYPE, 즐겨찾기 수 FAVORITES, 주소 ADDRESS,
## 리뷰 평균 점수 조회
## 리뷰 평균 점수 : 소수점 세 번째 자리에서 반올림
## 평균점수 기준 내림차순 -> 즐겨찾기 기준 내림차순

SELECT R.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_NAME
ORDER BY SCORE DESC, FAVORITES DESC

# SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS,
# ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO INFO
# JOIN REST_REVIEW REVIEW
# USING(REST_ID)
# WHERE INFO.ADDRESS LIKE "서울%"
# GROUP BY INFO.REST_ID
# ORDER BY INFO.REST_ID, INFO.FAVORITES