## FISH_INFO : 잡은 물고기들의 정보
## FISH_NAME_INFO : 물고기 이름 정보

## BASS와 SNAPPER의 수를 출력

SELECT COUNT(*) AS FISH_COUNT FROM FISH_INFO A
JOIN FISH_NAME_INFO B
USING(FISH_TYPE)
WHERE B.FISH_NAME = "BASS" OR B.FISH_NAME = "SNAPPER"