## USED_GOODS_BOARD  : 중고거래 게시판 정보
## USED_GOODS_REPLY : 게시판 첨부파일 정보

## 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일 조회
## 댓글 작성일 기준 오름차순 -> 게시글 제목 기준 오름차순

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R
USING(BOARD_ID)
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE, B.TITLE