## BOOK : 도서 정보
## BOOK_SALES : 판매 정보

## 2022년 1월 카테고리별 도서 판매량 합산
## 카테고리, 총 판매량 출력
## 카테고리 오름차순

SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
# SELECT *
FROM BOOK_SALES S LEFT JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.CATEGORY
ORDER BY CATEGORY