## 종류 별로 가장 큰 물고기 ID : ID, 이름 : FISH_NAME, 길이 출력 : LENGTH
SELECT ID
    , FISH_NAME
    , LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
USING (FISH_TYPE)
WHERE (I.FISH_TYPE, LENGTH)
IN (SELECT FISH_TYPE, MAX(LENGTH)
   FROM FISH_INFO
   GROUP BY FISH_TYPE)
ORDER BY ID