## ANIMAL_INS : 동물 보호소 "들어온" 동물정보
## ANIMAL_OUTS : 입양 "보낸" 동물정보

## 입양 간 기록 有 AND 들어온 기록 無 -> 동물 ID, 이름
## ID순으로 조회

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS LEFT JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID;